import React from 'react';
import {createRoot} from 'react-dom/client';
import {Home,BookOpen,Box,BrainCircuit,Landmark,Search,Bell,ChevronDown,ChevronRight,Sparkles,FileText,Upload,Send,Database,ChartNoAxesColumnIncreasing,ClipboardCheck,PenLine,ShieldCheck,CheckCircle2,Info,Paperclip,SlidersHorizontal,ExternalLink,CalendarDays,Users,Lightbulb} from 'lucide-react';
import './style.css';

function Shell(){return <><header><div className="brand"><div className="mark">岐</div><div><b>岐研</b><small>Qiyan Research Intelligence</small></div><span>中医临床研究智能平台</span></div><div className="search"><Search/><span>搜索课题、文献、研究问题或数据...</span></div><Bell className="bell"/><i></i><div className="avatar">王</div><div className="prof"><b>王教授</b><small>课题负责人</small></div><ChevronDown className="down"/></header><aside><nav><a><Home/>我的科研</a><a><BookOpen/>领域研究</a><a className="active"><BrainCircuit/>岐研 AI</a><a><Box/>科研资产</a><a><Landmark/>管理与治理</a></nav><div className="aihelp"><Sparkles/><div><b>岐研 AI 助手</b><small>随时为您的研究工作<br/>提供支持</small></div><ChevronRight/></div><div className="collapse">‹　收起菜单</div></aside></>}
const conversations=[['今天','针刺治疗抑郁的人组策略优化','10:24'],['','中心 03 入组下降的原因分析','09:15'],['','基于舌象的分型研究设计建议','08:40'],['最近 7 天','针灸治疗焦虑的证据汇总','04-20'],['','睡眠障碍的中西医结合方案','04-18'],['','研究方案统计分析方法咨询','04-17'],['','伦理审查常见问题','04-16'],['','针灸不良事件的文献分析','04-15'],['更早','针灸治疗情志病的研究趋势','04-10'],['','如何构建研究问题 (PICO)','04-08'],['','MSC 评分量表效应量场景','04-05']];
const causes=[['筛选失败率上升','研究数据','高','中心 03 近两周筛选 28 例，入组仅 4 例，失败率从 21% 上升至 38%。'],['研究医生变更/人力不足','中心反馈','高','3 月底核心研究医生请假，新医生尚在适应期。'],['患者来源减少','历史数据','中','门诊量较上月下降约 25%，与春季假期相关。'],['入排标准理解不一致','质控记录','中','近期发现 5 例因细节执行偏差未能入组。'],['患者顾虑增加','文献证据','中','类似研究中常见，主要与疗程时间和针刺治疗顾虑相关。']];
const evidence=[['针灸治疗抑郁症的临床疗效 Meta 分析','2023 · JAMA Psychiatry','高相关'],['多中心临床研究中入组影响因素分析','2022 · BMC Medical Research','中等相关'],['针刺治疗抑郁症的安全性与不良事件','2021 · Frontiers in Psychiatry','中等相关']];
function ConversationList(){return <section className="conversationList"><button className="newChat">＋　新建对话</button>{conversations.map((c,i)=><React.Fragment key={i}>{c[0]&&<div className="dateLabel">{c[0]}</div>}<div className={'conv '+(i===0?'selected':'')}><span>{c[1]}</span><time>{c[2]}</time></div></React.Fragment>)}</section>}
function ContextRail(){return <aside className="contextRail"><div className="railTitle"><b>当前研究上下文</b><a>切换研究 <ChevronRight/></a></div><section className="contextCard"><div className="studyName"><CalendarDays/><div><b>针刺抑郁多中心研究</b><small>ChiCTR230087654</small></div><em>进行中</em></div><dl><dt>研究类型</dt><dd>多中心 RCT</dd><dt>研究中心</dt><dd>5 个中心</dd><dt>计划入组</dt><dd>120 例</dd><dt>已入组</dt><dd><b>42 例 (35%)</b></dd><dt>研究周期</dt><dd>2024-01-15 ~ 2026-12-31</dd></dl></section><section className="ability"><b>可用能力</b>{[[FileText,'文献智能检索','基于领域知识的语义检索'],[ChartNoAxesColumnIncreasing,'数据分析与洞察','基于您的研究数据进行分析'],[ClipboardCheck,'研究设计建议','方案设计、统计方法、伦理建议'],[ShieldCheck,'方案与文档评审','识别问题并提供修改建议'],[PenLine,'写作辅助','论文、报告、摘要的撰写支持']].map(([I,t,s])=><div><I/><span><b>{t}</b><small>{s}</small></span></div>)}</section><section className="referenceState"><div className="railTitle"><b>参考范围与不确定性</b><a>了解更多 <ChevronRight/></a></div><p>◉ 参考文献　　8 篇（近 5 年）</p><p>□ 研究数据　　您当前研究的脱敏数据</p><p>△ AI 不确定性　 <em>中等</em></p><small>本回答基于现有证据和数据分析，可能存在不确定性，建议结合专家意见进行判断。</small></section><div className="railHint"><Lightbulb/><span><b>岐研 AI 是研究助手，</b><br/>重要决策请结合专业判断。</span></div></aside>}
function MainAnswer(){return <section className="chat"><div className="thread"><div className="userPrompt"><div className="userBubble"><span>中心 03 近两周入组速度下降 67%，请帮我分析可能的原因，并给出可行的改进建议。</span><time>10:24</time></div><div className="miniAvatar">王</div></div><div className="answer"><div className="aiAvatar"><Sparkles/></div><div className="answerBody"><div className="answerTitle"><b>岐研 AI</b><span>基于 8 条证据 · 结合本研究数据分析</span></div><p className="intro">我已结合您当前研究的运营数据、历史经验和相关文献进行了分析。以下是可能原因及改进建议：</p><div className="step"><i>1</i><b>可能原因分析</b></div><div className="causeTable"><div className="tr head"><span>可能原因</span><span>证据支持</span><span>相关性</span><span>说明</span></div>{causes.map((r,i)=><div className="tr" key={i}><b>{r[0]}</b><span>{r[1]}</span><span><em style={{width:i<2?'84%':i===2?'58%':'45%'}}></em><small>{r[2]}</small></span><span>{r[3]}</span></div>)}</div><div className="step"><i>2</i><b>改进建议</b></div><div className="suggestions">{['加强研究者培训：针对入排标准和评估量表进行再培训，提供操作手册和示例视频。','增加患者宣教：优化知情同意沟通话术，突出针刺治疗的安全性和已有证据。','调整入组策略：在符合伦理的前提下，扩大患者来源渠道（如合作门诊、社区转诊）。','加强中心支持：安排项目组远程或现场支持，帮助新研究医生快速熟悉流程。','持续监测：每周跟踪入组趋势，设置预警机制，及时干预。'].map(x=><p><CheckCircle2/><span>{x}</span></p>)}</div><div className="step evidenceHead"><i>3</i><b>相关证据（8 条）</b><a>查看全部 <ChevronRight/></a></div><div className="evidenceCards">{evidence.map((e,i)=><article><FileText/><b>{e[0]}</b><small>{e[1]}</small><em className={i===0?'high':''}>{e[2]}</em><div><span>RCT</span><span>Meta 分析</span></div></article>)}</div><div className="uncertainty"><Info/><span><b>不确定性：</b>中心 05 当前样本较少；本回答基于现有证据和数据分析，可能存在不确定性，任何方案变更均需要授权人员确认。</span></div></div></div></div><Composer/></section>}
function Composer(){
  const box = React.useRef(null);
  const grow = () => {
    const el = box.current;
    if (!el) return;
    const max = 200;
    el.style.height = 'auto';
    const next = Math.min(el.scrollHeight, max);
    el.style.height = `${next}px`;
    el.style.overflowY = el.scrollHeight > max ? 'auto' : 'hidden';
  };
  return <div className="composer"><div className="composerField"><textarea ref={box} rows={1} placeholder="继续提问，或输入其他研究问题..." onInput={grow}/><button type="button" aria-label="发送"><Send/></button></div><div className="composerTools"><button type="button"><Upload/> 上传文件</button><button type="button"><SlidersHorizontal/> 深度分析 <ChevronDown/></button><button type="button"><Search/> 联网检索</button><span>基于当前研究 <ChevronDown/></span></div></div>;
}
function App(){return <><Shell/><main className="platform-main"><section className="aiHeader"><div><h1>岐研 AI</h1><p>基于领域知识与您的研究上下文，提供证据化的分析、建议与研究设计支持。</p></div></section><div className="tabs"><b>对话</b><span>研究设计</span><span>文献检索</span><span>数据分析</span><span>方案评审</span><span>写作助手</span></div><div className="workspace"><ConversationList/><MainAnswer/><ContextRail/></div></main></>}
createRoot(document.getElementById('root')).render(<App/>);
