import React from 'react';import{createRoot}from'react-dom/client';import{Home,BookOpen,Box,BrainCircuit,Landmark,Search,Bell,ChevronDown,ChevronRight,Folder,AlertTriangle,ClipboardCheck,Sparkles,Clock,Bookmark,FileText,Lightbulb,Users,Activity,ArrowRight,CalendarDays}from'lucide-react';import'./style.css';
const C='#4f46e5';
function Nav(){return <><header><div className="brand"><div className="mark">岐</div><div><b>岐研</b><small>Qiyan Research Intelligence</small></div><span>中医临床研究智能平台</span></div><div className="search"><Search/><span>搜索课题、文献、研究问题或数据...</span></div><Bell className="bell"/><i></i><div className="avatar">王</div><div className="prof"><b>王教授</b><small>课题负责人</small></div><ChevronDown className="down"/></header><aside><nav><a className="active"><Home/>我的科研</a><a><BookOpen/>领域研究</a><a><BrainCircuit/>岐研 AI</a><a><Box/>科研资产</a><a><Landmark/>管理与治理</a></nav><div className="aihelp"><Sparkles/><div><b>岐研 AI 助手</b><small>随时为您的研究工作<br/>提供支持</small></div><ChevronRight/></div><div className="collapse">‹　收起菜单</div></aside></>}
const Stat=({icon,title,num,sub,alert,ai})=><div className={'stat '+(ai?'aiStat':'')}><div className="statTop">{icon}{title}</div><div className="statNum">{num}{alert&&<em>+1</em>}</div><small>{sub}</small></div>;
function Hub(){return <div className="hub"><div className="hubMain"><div className="hubIcon"><Landmark/></div><div><small>我发起的 Research Hub</small><div className="hubTitle">针灸治疗情志病 <span>Research Hub</span></div><p>探索针灸在抑郁、焦虑等情志疾病中的临床价值，构建高质量循证证据体系。</p><div className="hubMeta"><b>▣　3</b> 项研究　　<b>▣　18</b> 项科研资产　　<b>♙　1</b> 个潜在研究机会</div></div></div><div className="hubNews"><b>▥　领域最新变化</b><p>近两周发现 8 项相关证据，<br/>其中 2 项与您主持的抑郁症多中心<br/>研究高度相关。</p><button>进入领域研究　→</button></div></div>}
function Attention(){return <section className="attention"><div className="attHead"><span><AlertTriangle/>需要您判断</span><div><b>高优先级</b>　更新于 2 小时前　•••</div></div><div className="attBody"><small>针刺抑郁多中心研究</small><h2>近两周入组速度低于课题计划</h2><p>近 14 日完成入组 4 人，计划 12 人，较计划下降 <strong>67%</strong>。</p><div className="attGrid"><div className="metric"><small>当前入组进度</small><b><em>42</em> / 120</b><div className="bar"><i style={{width:'35%'}}/></div><span>35%</span></div><div className="metric"><small>近 14 日新增入组</small><div className="plan">12 <small>计划</small></div><b>4 <small>实际</small> <strong>↓ 67%</strong></b></div><div className="metric chart"><small>入组趋势（近 14 日）　　<span>▥ 计划　■ 实际</span></small><div className="bars">{[9,15,8,12,6,13,7,10,8,14,7,12].map((h,i)=><i key={i} style={{height:10+h}}/> )}</div><div className="dates">09-04　 09-07　 09-10　 09-13　 09-16</div></div><div className="impact"><small>可能影响</small><p><Clock/> 按当前速度，<br/>预计总体入组里程碑<br/>将延后的 4 周<br/>（基于当前趋势的预测）</p></div></div><div className="lower"><div className="deviation"><small>主要偏差中心（近两周）</small><div className="deviationCards"><article><b>中心 03</b><br/><span>计划 5 | 实际 1　 <strong>↓ 80%</strong></span></article><article><b>中心 05</b><br/><span>计划 3 | 实际 0　 <strong>↓ 100%</strong></span></article></div><div className="actions"><button>进入课题判断　↗</button><button>查看入组偏差</button><button>分配任务</button></div></div><div className="aiAnalysis"><div><Sparkles/> <b>岐研 AI 分析</b>　<span>基于 8 条证据</span></div><ul><li>入组下降主要集中在中心 03 和中心 05；</li><li>中心 03 近两周筛选失败率由 21% 上升至 38%；</li><li>这更可能与筛选转化下降有关，而非单纯访视排期问题。</li></ul><p>ⓘ　<b>尚不能确定：</b> 中心 05 当前样本较少，暂不能判断是否属于持续性趋势。</p><div className="aiFoot"><a>查看分析依据 · 8 条证据　→</a><span><Bookmark/> 标记为已阅</span></div></div></div></div></section>}
const briefs=[['高相关','针灸治疗抑郁症的最新 Meta 分析结果','纳入 22 项 RCT，显示针灸在改善抑郁症状方面具有显著疗效。','与你的研究相关：可为当前方案的次要结局提供参考'],['中等相关','长期随访与患者报告结局的报告方式正在发生变化','与针刺抑郁多中心研究的次要结局和长期随访设计相关。','形成研究机会：可探索更适合中医研究的 PRO 方案'],['潜在研究机会','针灸与正念联合干预的研究空白','近年来正念干预可能具有协同效应，值得探索。','基于 6 篇证据，岐研 AI 建议形成新研究机会']];
function Brief(){return <><div className="briefTitle"><b>与你相关的研究简报</b><span>近 12 个月 · 8 项来源</span><a>查看全部 →</a></div><div className="briefs">{briefs.map((x,i)=><article key={x[1]}><div><span className={'tag t'+i}>{x[0]}</span></div><b><FileText/>{x[1]}</b><p>{x[2]}</p><a>{x[3]}　→</a></article>)}</div></>}
const projects=[['针刺抑郁多中心研究','执行中','3 / 5 中心　　42 / 120 已入组','35%'],['针灸联合睡眠干预观察','方案设计','待团队评议',''],['中医情志病真实世界研究','执行中','2 / 3 中心　 128 / 300 已入组','43%'],['基于舌象的抑郁症分型研究','方案设计','方案完善中',''],['针灸治疗失眠的多中心 RCT','已完成','已完成研究 · 论文撰写中','']];
function Rail(){return <div className="rail"><div className="railCard"><div className="railTitle"><b>我的课题</b><a>查看全部（5）→</a></div>{projects.map((p,i)=><div className="project" key={p[0]}><div className="picon">{i===0?<CalendarDays/>:<Box/>}</div><div><b>{p[0]}</b><small>{p[2]}</small>{p[3]&&<div className="pbar"><i style={{width:p[3]}}/></div>}</div><span className={'state s'+i}>{p[1]}</span>{p[3]&&<em>{p[3]}</em>}</div>)}</div><div className="railCard recent"><div className="railTitle"><b>近期重要动态</b><a>查看全部 →</a></div>{[['⚠','中心 03 筛选失败率上升','6 小时前'],['▣','1 项新研究证据已入库','1 天前'],['▥','团队提交了方案修订建议','1 天前'],['▥','领域内发布 3 篇相关文献','2 天前'],['♧','岐研 AI 发现 1 个潜在研究机会','2 天前']].map(x=><div className="event"><span>{x[0]}</span><b>{x[1]}</b><small>{x[2]}</small></div>)}</div></div>}
function App(){return <><Nav/><main><div className="hello"><div><h1>王教授，您好</h1><p>专注于证据，推动更好的临床实践。</p></div><div><b>2026 年 9 月 18 日　星期五</b></div></div><div className="workspace"><div className="center"><Hub/><div className="stats"><Stat icon={<Folder/>} title="我的课题" num="5 项" sub="进行中 3 | 方案设计 1 | 已完成 1"/><Stat icon={<AlertTriangle/>} title="需要判断" num="2 项" alert sub="较上周"/><Stat icon={<ClipboardCheck/>} title="待我处理" num="1 项" sub="审批 / 评议 / 确认"/><Stat ai icon={<BrainCircuit/>} title="岐研 AI" num="" sub="已理解您的研究上下文　›\n今日更新 12 条新证据"/></div><Attention/><Brief/></div><Rail/></div></main></>};createRoot(document.getElementById('root')).render(<App/>);
