import p1 from './photos/p1.png';
import p2 from './photos/p2.png';
import p3 from './photos/p3.png';
import p4 from './photos/p4.png';
import p5 from './photos/p5.png';

export const PEOPLE = [
  {
    id: 'wang',
    name: '王某教授',
    rank: '教授 / 博士生导师',
    badges: ['教授', '博士生导师'],
    org: '北京中医药大学 针灸推拿学院',
    dept: '针灸推拿学院',
    city: '北京',
    orgType: '高校',
    level: '高相关',
    photo: p1,
    email: 'wang@bucm.edu.cn',
    phone: '010-0002-1234',
    summary: '专注于针灸治疗抑郁障碍的机制研究与临床转化，开展多中心随机对照试验、真实世界研究及神经生物学机制研究。',
    intro: '王某教授长期从事抑郁障碍的中西医结合研究，重点开展针灸干预的神经机制研究。其团队在多中心随机对照试验、神经影像和生物标志物研究方面积累了系统证据，推动针灸在情志障碍领域的临床应用与机制阐释。',
    tags: ['抑郁障碍', '针灸治疗', '神经影像', '临床试验', '机制研究'],
    papers: 286,
    trials: 12,
    projects: 8,
    hindex: 28,
    teamId: 'bucm',
    teamName: '北京中医药大学 针灸推拿学院抑郁障碍研究团队',
    teamRole: '团队负责人',
    role: 'PI / 负责人',
    relevance: [
      '在抑郁障碍领域持续开展针灸干预研究',
      '发表多篇针灸治疗抑郁障碍的高质量论文',
      '承担国家级/省部级相关课题',
      '开展多中心临床试验并纳入神经影像研究',
    ],
    directionKind: '归纳',
    directions: [
      ['抑郁障碍的针灸干预', '临床疗效、个体化治疗方案'],
      ['神经机制研究', '脑功能影像、神经递质、神经可塑性'],
      ['临床试验与真实世界研究', '多中心RCT、真实世界研究、疗效与安全性评价'],
      ['中医现代化', '针灸标准化、循证评价、临床转化'],
    ],
    hubDimensions: [
      ['疾病方向', '抑郁障碍', 'match'],
      ['干预方向', '针灸', 'match'],
      ['临床研究', 'RCT', 'match'],
      ['机制研究', '神经影像', 'match'],
    ],
    works: [
      ['Acupuncture for moderate-to-severe depression: a multicenter randomized controlled trial', 'Wang XX, Li XX, Zhang XX, et al.', 'JAMA Psychiatry 2022', '被引 152'],
      ['Neural mechanisms of acupuncture in depression: evidence from resting-state fMRI', 'Li XX, Wang XX, et al.', 'NeuroImage 2022', '被引 98'],
      ['Individualized acupuncture treatment for depression based on machine learning', 'Zhang XX, Wang XX, et al.', 'Brain Stimulation 2021', '被引 76'],
    ],
    trialRows: [
      ['针灸联合常规治疗抑郁障碍的多中心随机对照试验', 'ChiCTR2300071234', '多中心 RCT', '招募中'],
      ['电针调节前额叶功能的神经影像研究', 'ChiCTR2200067890', '单中心 RCT', '招募中'],
      ['针灸治疗青少年抑郁障碍的真实世界研究', 'ChiCTR2300083456', '前瞻性观察', '招募中/进行中'],
    ],
    guides: ['抑郁障碍针灸干预临床路径（草案）', '针灸治疗抑郁障碍证据综述', '情志病针灸临床试验报告规范', '抑郁障碍中西医结合诊疗共识要点', '针灸个体化方案制定建议', '多中心针灸试验质量控制要点'],
    affiliations: [
      { current: true, org: '北京中医药大学', unit: '针灸推拿学院', title: '教授', period: '2020 – 至今' },
      { current: false, org: '北京中医药大学', unit: '针灸推拿学院', title: '副教授', period: '2015 – 2020' },
    ],
    education: [
      { period: '2010 – 2015', text: '北京中医药大学 中医学院 博士' },
      { period: '2004 – 2010', text: '北京中医药大学 中医学 学士' },
    ],
    posts: ['北京中医药大学 针灸推拿学院 教授', '博士生导师', '抑郁障碍研究团队 团队负责人'],
    projectNames: ['针灸治疗抑郁障碍的多中心随机对照研究', '电针调节前额叶功能的神经影像研究', '针灸个体化方案与生物标志物研究'],
    partners: ['上海交通大学医学院附属精神卫生中心', '华中科技大学同济医学院附属同济医院', '四川大学华西医院'],
  },
  {
    id: 'li',
    name: '李某教授',
    rank: '教授 / 主任医师',
    badges: ['教授', '主任医师'],
    org: '上海交通大学医学院',
    dept: '精神卫生中心',
    city: '上海',
    orgType: '高校',
    level: '高相关',
    photo: p2,
    email: 'limou@sjtu.edu.cn',
    phone: '021-0002-1234',
    summary: '聚焦抑郁障碍的临床研究与转化医学，开展药物、心理治疗及物理治疗的多模式联合干预研究。',
    tags: ['抑郁障碍', '心理治疗', '药物治疗', '临床队列', '转化医学'],
    papers: 342,
    trials: 19,
    projects: 15,
    hindex: 36,
    teamId: 'sjtu',
    teamName: '上海交通大学医学院附属精神卫生中心抑郁障碍研究团队',
    teamRole: '团队负责人',
    role: 'PI / 负责人',
    works: [
      ['抑郁障碍多模态联合干预的真实世界研究', '李某教授 等', '2023', ''],
      ['生物标志物指导的个体化治疗研究', '李某教授 等', '2022', ''],
    ],
  },
  {
    id: 'zhang',
    name: '张某教授',
    rank: '教授 / 主任医师',
    badges: ['教授', '主任医师'],
    org: '中南大学湘雅二医院',
    dept: '精神卫生研究所',
    city: '长沙',
    orgType: '医院',
    level: '相关',
    photo: p3,
    email: 'zhangmou@csu.edu.cn',
    phone: '0731-0002-1234',
    summary: '专注于抑郁障碍和焦虑障碍的临床与基础研究，开展神经影像、生物标志物及临床干预研究。',
    tags: ['抑郁障碍', '焦虑障碍', '神经影像', '生物标志物', '临床数据库'],
    papers: 318,
    trials: 16,
    projects: 12,
    hindex: 31,
    teamId: 'xiangya',
    teamName: '中南大学湘雅二医院情绪障碍研究团队',
    teamRole: '团队负责人',
    role: 'PI / 负责人',
    works: [
      ['抑郁障碍脑影像标志物的多中心研究', '张某教授 等', '2023', ''],
      ['基于机器学习的抑郁症预测模型', '张某教授 等', '2022', ''],
    ],
  },
  {
    id: 'liu',
    name: '刘某教授',
    rank: '教授 / 主任医师',
    badges: ['教授', '主任医师'],
    org: '四川大学华西医院',
    dept: '心理卫生中心',
    city: '成都',
    orgType: '医院',
    level: '相关',
    photo: p4,
    email: 'liumou@wchscu.cn',
    phone: '028-0002-1234',
    summary: '开展抑郁障碍的临床流行病学、干预研究及机制研究，关注青少年抑郁、难治性抑郁和共病问题。',
    tags: ['抑郁障碍', '青少年心理健康', '临床干预', '流行病学', '共病研究'],
    papers: 274,
    trials: 14,
    projects: 10,
    hindex: 27,
    teamId: 'huaxi',
    teamName: '四川大学华西医院心理卫生中心研究团队',
    teamRole: '团队负责人',
    role: 'PI / 负责人',
    works: [
      ['青少年抑郁障碍的纵向队列研究', '刘某教授 等', '2023', ''],
      ['难治性抑郁的联合治疗策略研究', '刘某教授 等', '2022', ''],
    ],
  },
  {
    id: 'chen',
    name: '陈某教授',
    rank: '教授 / 主任医师',
    badges: ['教授', '主任医师'],
    org: '华中科技大学同济医学院附属同济医院',
    dept: '精神医学科',
    city: '武汉',
    orgType: '医院',
    level: '相关',
    photo: p5,
    email: 'chenmou@tjh.tjmu.edu.cn',
    phone: '027-0002-1234',
    summary: '聚焦抑郁障碍的临床诊疗与神经机制研究，开展脑功能成像、神经调控及数字医疗研究。',
    tags: ['抑郁障碍', '神经调控', '脑功能成像', '数字医疗', '临床应用'],
    papers: 195,
    trials: 8,
    projects: 6,
    hindex: 22,
    teamId: 'tongji',
    teamName: '华中科技大学同济医学院附属同济医院精神医学研究团队',
    teamRole: '团队负责人',
    role: 'PI / 负责人',
    works: [
      ['经颅磁刺激治疗抑郁障碍的多中心研究', '陈某教授 等', '2023', ''],
      ['数字化干预在抑郁障碍中的应用研究', '陈某教授 等', '2022', ''],
    ],
  },
];

export function openResearcher(id) {
  window.location.assign(`/pages/r02/?id=${id}`);
}
